### ISSUE TITLE
Execution Time

### ISSUE THREAD

**Issue by davidcastells** [preusser/q27#7]
Hi Thomas, could you include any information about the total execution time that it took to get the Q27 solutions?
For Q26, you reported 8 months and I counted 368 solvers.

For Q27 I count 2747 solvers, but I guess what is the execution time ? an approximate number (months, years (?) ) would be ok.

BR.

**Comment by preusser** [comment]
Hi David,
as stated in the last news post, the computation was running slightly over a year. I was actually starting the computation during the FPL 2015 in London, so the year was exceeded by 17 days. You seem to be miscounting the solvers though. We had four of these DNK7_F5_PCIe workhorses, each of them already contributing 1200 solvers at 220 MHz. Whatever way you choose to add in the hardware running at other clock speeds, you should certainly not end up below a count of 5000.

**Comment by davidcastells** [comment]
So the numbers could be around the below numbers?

For Q26 -> 368 solvers during 8 months 
For Q27 -> 5000 solvers during 12 months

I will try to get an estimation of the invested time (seconds) per solution (TPS), which would be something like

TPS = (Total Time * Solvers) / Solutions

If the above numbers are correct, seems to be something like 
TPS_Q26 ≈ 0.34 us
TPS_Q27 ≈ 0.66 us

**Comment by preusser** [comment]
For a rough estimate, this will certainly do.
